// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"trx-project/internal/api/handler/frontendHandler"
	"trx-project/internal/repository"
	"trx-project/internal/service"
	"trx-project/pkg/config"

	"github.com/gin-gonic/gin"

	_ "trx-project/cmd/frontend/docs"
)

// Injectors from wire.go:

// initFrontendApp initializes the frontend application with all dependencies
func initFrontendApp(cfg *config.Config) (*gin.Engine, func(), error) {
	logger, err := provideLogger(cfg)
	if err != nil {
		return nil, nil, err
	}
	db, err := provideDB(cfg, logger)
	if err != nil {
		return nil, nil, err
	}
	userRepository := repository.NewUserRepository(db)
	client, err := provideRedis(cfg, logger)
	if err != nil {
		return nil, nil, err
	}
	jwtConfig := provideJWTConfig(cfg)
	userService := service.NewUserService(userRepository, client, logger, jwtConfig)
	userHandler := frontendHandler.NewUserHandler(userService, logger)
	engine := provideFrontendRouter(userHandler, client, logger, cfg)
	return engine, func() {
	}, nil
}
