// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"trx-project/internal/api/handler/backendHandler"
	"trx-project/internal/repository"
	"trx-project/internal/service"
	"trx-project/pkg/cache"
	"trx-project/pkg/config"

	"github.com/gin-gonic/gin"

	_ "trx-project/cmd/backend/docs"
)

// Injectors from wire.go:

// initBackendApp initializes the backend application with all dependencies
func initBackendApp(cfg *config.Config) (*gin.Engine, func(), error) {
	logger, err := provideLogger(cfg)
	if err != nil {
		return nil, nil, err
	}
	db, err := provideDB(cfg, logger)
	if err != nil {
		return nil, nil, err
	}
	userRepository := repository.NewUserRepository(db)
	client, err := provideRedis(cfg, logger)
	if err != nil {
		return nil, nil, err
	}
	jwtConfig := provideAdminJWTConfig(cfg)
	userService := service.NewUserService(userRepository, client, logger, jwtConfig)
	adminUserHandler := backendHandler.NewAdminUserHandler(userService, logger)
	rbacRepository := repository.NewRBACRepository(db)
	rbacCache := cache.NewRBACCache(client, logger)
	rbacService := service.NewRBACService(rbacRepository, rbacCache, logger)
	rbacHandler := backendHandler.NewRBACHandler(rbacService, logger)
	engine := provideBackendRouter(adminUserHandler, rbacHandler, rbacService, client, logger, cfg)
	return engine, func() {
	}, nil
}
