// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"github.com/redis/go-redis/v9"
	"go.uber.org/zap"
	"gorm.io/gorm"
	"time"
	"trx-project/internal/api/handler"
	"trx-project/internal/api/router"
	"trx-project/internal/repository"
	"trx-project/internal/service"
	"trx-project/pkg/cache"
	"trx-project/pkg/config"
	"trx-project/pkg/database"
	"trx-project/pkg/jwt"
	"trx-project/pkg/logger"
)

// Injectors from wire.go:

// initBackendApp initializes the backend application with all dependencies
func initBackendApp(cfg *config.Config) (*gin.Engine, func(), error) {
	logger, err := provideLogger(cfg)
	if err != nil {
		return nil, nil, err
	}
	db, err := provideDB(cfg, logger)
	if err != nil {
		return nil, nil, err
	}
	userRepository := repository.NewUserRepository(db)
	client, err := provideRedis(cfg, logger)
	if err != nil {
		return nil, nil, err
	}
	jwtConfig := provideAdminJWTConfig(cfg)
	userService := service.NewUserService(userRepository, client, logger, jwtConfig)
	adminUserHandler := handler.NewAdminUserHandler(userService, logger)
	rbacRepository := repository.NewRBACRepository(db)
	rbacService := service.NewRBACService(rbacRepository, logger)
	rbacHandler := handler.NewRBACHandler(rbacService, logger)
	engine := provideBackendRouter(adminUserHandler, rbacHandler, rbacService, logger, cfg)
	return engine, func() {
	}, nil
}

// wire.go:

// initLogger initializes logger for output
func initLogger(cfg *config.Config) (*zap.Logger, error) {
	return provideLogger(cfg)
}

func provideLogger(cfg *config.Config) (*zap.Logger, error) {
	if err := logger.InitLogger(&cfg.Logger); err != nil {
		return nil, err
	}
	return logger.Logger, nil
}

func provideDB(cfg *config.Config, logger2 *zap.Logger) (*gorm.DB, error) {
	return database.InitMySQL(&cfg.Database.MySQL, logger2)
}

func provideRedis(cfg *config.Config, logger2 *zap.Logger) (*redis.Client, error) {
	return cache.InitRedis(&cfg.Redis, logger2)
}

func provideAdminJWTConfig(cfg *config.Config) jwt.Config {
	return jwt.Config{
		Secret:     cfg.JWT.Secret,
		Issuer:     cfg.JWT.Issuer,
		ExpireTime: time.Duration(cfg.JWT.AdminExpireHours) * time.Hour,
	}
}

func provideBackendRouter(
	adminUserHandler *handler.AdminUserHandler,
	rbacHandler *handler.RBACHandler,
	rbacService service.RBACService, logger2 *zap.Logger,
	cfg *config.Config,
) *gin.Engine {
	return router.SetupBackend(adminUserHandler, rbacHandler, rbacService, cfg.JWT.Secret, logger2, cfg.Server.Mode)
}
